### PR TITLE
Upgrade to Metamask 5.3.0

### PR DESCRIPTION
**Pull request by lionseal**
Hi all, great project! I couldn't fully use it because of the Metamask version, so I took the time to upgrade to Metamask 5.3.0

There are some breaking changes, now metamask requires you to create an account at the beginning so, now you need to pass a seed, or, I added a default seed (the one in the examples).

I also added a new method to switch accounts.

The test the project has do not work with either versions as decentraland settings page has changed. I tested with the project I'm currently working on, and everything seems fine.

Let me know what you guys think, this is also my first pull request so I'm not really sure if this is the way to request one.

### CODE REVIEW

**Comment by zlyojciec** [comment]
Hey @lionseal great update 👍 

Will you be able to update custom gas/gasLimit options?

Thanks!

**Comment by lionseal** [comment]
Hi @zlyojciec, thanks! I had some WIP, I'll add it as soon as I have time to finish and test it

**Comment by zlyojciec** [comment]
Hey @lionseal Thanks for quick response. 
Finally i have decided to create a `fake wallet provider` based on Ethersjs. This approach gives me ability to work on different e2e test engines and all transactions are confirmed automaticly.

Also having my own provider i can override `estimateGas` gas method to temporary fix Ganche issues with gasLimit - [https://github.com/trufflesuite/ganache-cli/issues/592](https://github.com/trufflesuite/ganache-cli/issues/592)

**Comment by lionseal** [comment]
Hi again! I added the custom gas and gas limit options to confirmTransaction method, both are optional, and leave the default values if they are not set when passing the options object.

Also updated the test with a custom ganache node, rocketh, and mocha.

Cheers

**Comment by cazala** [comment]
You are a hero, sir 🥇

**Comment by cazala** [comment]
released `dappeteer@0.4.0`

**Pull request merged**
