### PR TITLE
Migrate to use Metamask v8 or v9

### PR DESCRIPTION
**Pull request by dasanra**
### Added
 - Changes to add compatibility with latest Metamask versions  (currently v8.1.11 and v9.0.4)
 - **BREAKING CHANGE** use `puppeteer@5.5.0` as peer dependency
 - **BREAKING CHANGE** only `node >=10.12` and `node < 11` support for building this package.
 - Option to approve all accounts when connecting from Dapp for the first time (is very difficult to get to this modal once an account is connected because Metamask remembers this decision and only connects to that account. If you want the switchAccount method to work, you need to authorize all accounts when connecting for the first time)

### Chore
 - Bump devDependencies
 
 
 #### How to review this PR?
 Most of the file changes are under `metamask` folder. I've just added the corresponding zips from latest v8 and v9 Chrome versions.
Once we scroll below `metamask` folder files we can check the real changes that were applied to the project
  
 #### Recommended to publish using a major version v2.0.0

### CODE REVIEW

**Review by sriharikapu — APPROVED** [review]

**Review by sriharikapu — APPROVED** [review]
This looks good

**Review by sriharikapu — APPROVED** [review]
Although there are few minor issues with the checkbox's on the Metamask v9. It still works fine.

**Comment by cazala** [comment]
Hey guys, thanks for the PR, i’m currently on vacation, but next week i’ll test and merge/release this if all’s good.

**Comment by dasanra** [comment]
> Although there are few minor issues with the checkbox's on the Metamask v9. It still works fine.

Yes, detected this while working on my project. I expect to add a fix during this week 👍

**Comment by dasanra** [comment]
@sriharikapu I added a fix for the account checkbox in `approve` method, hope it works for you!

**Review by sriharikapu — APPROVED** [review]

**Review by sriharikapu — APPROVED** [review]

**Comment by jpangelle** [comment]
Trying to use this branch in a project using `yarn 2` which is not compatible with `node >=10.12` and `node < 11`. Curious on why this can only be used with those versions of node.

**Pull request closed without merging**
