### PR TITLE
Metamask 7.7.1

### PR DESCRIPTION
**Pull request by fleupold**
This PR updates the bundled version inside dappeteer to the most recent Metamask version (v7.7.1).

This allows features (e.g. reading the chainId), on which some modern dapps (like ours 😉) rely. 
Dappeteer's interface to interact with metamask stays unchanged thus tests built against older versions should continue working.

To make reviewing easier, I split this PR into two commits - one that just replaces the Metamask source and another one changing the dappeteer selectors/logic.

I created a chrome build as described here: https://github.com/MetaMask/metamask-extension/tree/v7.7.1#building-locally

### TestPlan

```
yarn/npm test
```

### CODE REVIEW

**Comment by fleupold** [comment]
Hi @cazala is this PR something you could see being merged? 

We want to use your framework for our frontend e2e tests but rely on some newer Metamask features which are not supported by the current version.

Please let me know if there is anything I can do to make this PR easier to review.

**Comment by cazala** [comment]
Hi @fleupold! I'm sorry for the late response, I went on vacations the day after you first PR for a couple weeks and then I came back and I didn't notice this second one until now. I tried running the tests on this branch but they get stuck in metamask's welcome screen:

Screen Shot 2020-01-23 at 12 11 56 PM

Maybe there's something I'm missing?

This is what i did:

```
cd dappeteer
git checkout -b fleupold-metamask_7.7.1 master
git pull https://github.com/fleupold/dappeteer.git metamask_7.7.1
npm i
npm test
```

**Comment by cazala** [comment]
The tests fail on the console with a timeout:

```
Starting ganache...
Ganache running at http://localhost:8545
Starting test server...
Server running at http://localhost:8080
Deploying test contract...
Contract deployed at 0x0fC7E4bD0784Af9b444015557CDBdA05d9D4D46e
/Users/juancazala/code/dappeteer/src/metamask/7.7.1
  1) "before all" hook

  0 passing (3m)
  1 failing

  1) "before all" hook:
     Error: Timeout of 200000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by fleupold** [comment]
Hi @cazala, thanks for checking it out. The problem turns out to be that the chrome-extension id was different on my local machine for some reason.

I'm updating PR to use a regex instead to make it extension-id agnostic.

**Comment by fleupold** [comment]
@cazala any chance you can do another review here?

<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia2.giphy.com%2Fmedia%2FljKQFspq8snkI%2Fgiphy.gif&token=ping" data-gitmeme-token="ping"></a>

**Comment by cazala** [comment]
Screen Shot 2020-02-19 at 3 26 19 PM

Dude sorry for taking so long I totally missed your previous comment 🙏 thank you!! 🥇

**Comment by cazala** [comment]
Released in version `1.0.0` 🚀

**Pull request merged**
